/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class", 
  theme: { 
    extend: { 

      "borderRadius": { 
        "DEFAULT": "0.25rem", 
        "lg": "0.5rem", 
        "xl": "0.75rem", 
        "full": "9999px" 
      }, 
      "spacing": { 
        "gutter-tablet": "1.5rem", 
        "section-gap-md": "5rem", 
        "margin-mobile": "1rem", 
        "section-gap-sm": "3rem", 
        "margin-tablet": "2rem", 
        "gutter-mobile": "1rem", 
        "section-gap-lg": "7.5rem", 
        "gutter-desktop": "2rem", 
        "margin-desktop": "5rem" 
      }, 
      "fontFamily": { 
        "sans": ['"Plus Jakarta Sans"', 'sans-serif'],
        "sinhala": ['"Noto Sans Sinhala"', '"Plus Jakarta Sans"', 'sans-serif'],
        "label-md": ["plusJakartaSans"], 
        "headline-xl-mobile": ["plusJakartaSans"], 
        "display-hero": ["plusJakartaSans"], 
        "headline-xl": ["plusJakartaSans"], 
        "body-sm": ["inter"], 
        "headline-md": ["plusJakartaSans"], 
        "body-md": ["inter"], 
        "body-lg": ["inter"], 
        "headline-lg": ["plusJakartaSans"], 
        "title-sm": ["plusJakartaSans"], 
        "label-xs": ["plusJakartaSans"], 
        "display-hero-mobile": ["plusJakartaSans"] 
      }, 
      "colors": { 
        "brand": {
          "navy": "#0b1d3a",
          "blue": "#0099ff",
          "emerald": "#00b074",
          "orange": "#ff9500",
          "violet": "#5856d6",
          "magenta": "#ff007f",
          "leaf": "#00c853",
          "amber": "#ffb300",
          "red": "#ff1a1a",
          "50": "#eff6ff",
          "100": "#dbeafe",
          "500": "#3b82f6",
          "600": "#2563eb",
          "700": "#1d4ed8",
          "800": "#1e40af",
          "900": "#1e3a8a"
        },
        "viduneth": {
          "dark": "#081c3b",
          "navy": "#0b2554",
          "accent": "#ff2d55"
        },
        "accent": {
          "gold": "#f59e0b",
          "emerald": "#10b981"
        },
        "subtle": "#f1f5f9",
        "secondary-fixed": "#e9ddff", 
        "surface": "#faf8ff", 
        "on-primary": "#ffffff", 
        "tertiary-fixed-dim": "#ffb2b7", 
        "surface-tint": "#0053db", 
        "on-error-container": "#93000a", 
        "inverse-on-surface": "#eef0ff", 
        "error-container": "#ffdad6", 
        "inverse-surface": "#283044", 
        "on-surface": "#131b2e", 
        "primary-container": "#2563eb", 
        "on-background": "#131b2e", 
        "secondary-container": "#8455ef", 
        "tertiary-fixed": "#ffdadb", 
        "on-primary-fixed-variant": "#003ea8", 
        "surface-container-low": "#f2f3ff", 
        "on-tertiary-fixed-variant": "#92002a", 
        "outline-variant": "#c3c6d7", 
        "inverse-primary": "#b4c5ff", 
        "primary-fixed-dim": "#b4c5ff", 
        "on-secondary-fixed": "#23005c", 
        "on-surface-variant": "#434655", 
        "surface-dim": "#d2d9f4", 
        "on-tertiary-container": "#ffecec", 
        "on-secondary-container": "#fffbff", 
        "secondary-fixed-dim": "#d0bcff", 
        "tertiary": "#ad0033", 
        "on-error": "#ffffff", 
        "surface-variant": "#dae2fd", 
        "background": "#faf8ff", 
        "outline": "#737686", 
        "surface-container-lowest": "#ffffff", 
        "error": "#ba1a1a", 
        "on-secondary-fixed-variant": "#5516be", 
        "primary-fixed": "#dbe1ff", 
        "primary": "#004ac6", 
        "on-primary-fixed": "#00174b", 
        "on-tertiary-fixed": "#40000d", 
        "surface-container-highest": "#dae2fd", 
        "on-tertiary": "#ffffff", 
        "surface-container": "#eaedff", 
        "on-primary-container": "#eeefff", 
        "tertiary-container": "#d22348", 
        "surface-bright": "#faf8ff", 
        "secondary": "#6b38d4", 
        "surface-container-high": "#e2e7ff", 
        "on-secondary": "#ffffff" 
      }, 
      "boxShadow": {
        "pill": "0 10px 30px -5px rgba(0, 0, 0, 0.08), 0 4px 6px -2px rgba(0, 0, 0, 0.03)",
        "glow-blue": "0 8px 18px -2px rgba(0, 153, 255, 0.45)",
        "glow-emerald": "0 8px 18px -2px rgba(0, 176, 116, 0.45)",
        "glow-orange": "0 8px 18px -2px rgba(255, 149, 0, 0.45)",
        "glow-violet": "0 8px 18px -2px rgba(88, 86, 214, 0.45)",
        "glow-magenta": "0 8px 18px -2px rgba(255, 0, 127, 0.45)",
        "glow-leaf": "0 8px 18px -2px rgba(0, 200, 83, 0.45)",
        "glow-amber": "0 8px 18px -2px rgba(255, 179, 0, 0.45)",
        "glow-red": "0 8px 18px -2px rgba(255, 26, 26, 0.45)",
        "glass": "0 20px 40px -15px rgba(2, 132, 199, 0.07), 0 0 1px 1px rgba(255, 255, 255, 0.9)",
        "card": "0 12px 35px -8px rgba(15, 23, 42, 0.08), 0 4px 12px -2px rgba(15, 23, 42, 0.03)",
        "glow": "0 0 25px -5px rgba(56, 189, 248, 0.35)",
        "soft": "0 4px 25px -4px rgba(0, 0, 0, 0.05), 0 2px 10px -2px rgba(0, 0, 0, 0.03)",
        "input": "0 1px 2px 0 rgba(0, 0, 0, 0.03)"
      },
      "fontSize": { 
        "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "600" }], 
        "headline-xl-mobile": ["28px", { "lineHeight": "36px", "letterSpacing": "-0.01em", "fontWeight": "700" }], 
        "display-hero": ["56px", { "lineHeight": "64px", "letterSpacing": "-0.03em", "fontWeight": "800" }], 
        "headline-xl": ["40px", { "lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "700" }], 
        "body-sm": ["13px", { "lineHeight": "20px", "fontWeight": "400" }], 
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }], 
        "body-md": ["15px", { "lineHeight": "24px", "fontWeight": "400" }], 
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }], 
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.015em", "fontWeight": "600" }], 
        "title-sm": ["18px", { "lineHeight": "24px", "fontWeight": "600" }], 
        "label-xs": ["11px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "700" }], 
        "display-hero-mobile": ["36px", { "lineHeight": "44px", "letterSpacing": "-0.02em", "fontWeight": "800" }] 
      } 
    } 
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
